/* generated by template cd2java.Class*/

/* (c) https://github.com/MontiCore/monticore */

/* Hookpoint: ClassContent:addComment */

/* generated by template cd2java.Package*/
package OnlineShop;


/* generated by template cd2java.Imports*/

import java.util.*;



/* Hookpoint: ClassContent:Imports */

/* generated by template cd2java.JavaDoc*/


/* generated by template cd2java.Annotations*/


/* Hookpoint: ClassContent:Annotations */

 class Discount   {

/* Hookpoint: ClassContent:Elements */

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 int discountID
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 String code
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 String description
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 double value
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 Date startDate
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 Date endDate
  /* generated by template cd2java.Value*/

;




}
