/* generated by template cd2java.Class*/

/* (c) https://github.com/MontiCore/monticore */

/* Hookpoint: ClassContent:addComment */

/* generated by template cd2java.Package*/
package OnlineShop;


/* generated by template cd2java.Imports*/

import java.util.*;



/* Hookpoint: ClassContent:Imports */

/* generated by template cd2java.JavaDoc*/


/* generated by template cd2java.Annotations*/


/* Hookpoint: ClassContent:Annotations */

 class Order   {

/* Hookpoint: ClassContent:Elements */

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 int orderID
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 double totalAmount
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 String status
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 String shippingAddress
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 Set<OnlineShop.OrderItem> orderItem
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 OnlineShop.Payment payment
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 OnlineShop.Shipment shipment
  /* generated by template cd2java.Value*/

;




}
