/* generated by template cd2java.Class*/

/* (c) https://github.com/MontiCore/monticore */

/* Hookpoint: ClassContent:addComment */

/* generated by template cd2java.Package*/
package OnlineShop;


/* generated by template cd2java.Imports*/

import java.util.*;



/* Hookpoint: ClassContent:Imports */

/* generated by template cd2java.JavaDoc*/


/* generated by template cd2java.Annotations*/


/* Hookpoint: ClassContent:Annotations */

 class OrderItem   {

/* Hookpoint: ClassContent:Elements */

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 int orderItemID
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 int quantity
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 double unitPrice
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 double totalPrice
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 OnlineShop.Product product
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 Optional<OnlineShop.Discount> discount
  /* generated by template cd2java.Value*/

;




}
