/* generated by template cd2java.Class*/

/* (c) https://github.com/MontiCore/monticore */

/* Hookpoint: ClassContent:addComment */

/* generated by template cd2java.Package*/
package OnlineShop;


/* generated by template cd2java.Imports*/

import java.util.*;



/* Hookpoint: ClassContent:Imports */

/* generated by template cd2java.JavaDoc*/


/* generated by template cd2java.Annotations*/


/* Hookpoint: ClassContent:Annotations */

 class Payment   {

/* Hookpoint: ClassContent:Elements */

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 int paymentID
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 String paymentMethod
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 double amount
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 Date paymentDate
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 String status
  /* generated by template cd2java.Value*/

;

    /* generated by template cd2java.Attribute*/
/* generated by template cd2java.JavaDoc*/

/* generated by template cd2java.Annotations*/

/* Hookpoint: AttributeContent:Annotations */
 String transactionID
  /* generated by template cd2java.Value*/

;




}
